### ISSUE TITLE
UTF-16BE to UTF-8 error

### ISSUE THREAD

**Issue by oleander** [oleander/Spot#1]
```
Exception JSON::ParserError -> Caught Encoding::ConverterNotFoundError at '}], "track-number": ': code converter not found (UTF-16BE to UTF-8)
```

Vet du vad felet kan bero på?

**Comment by Burgestrand** [comment]
Misstänker att det är samma som tidigare. Ifall en encoding inte är satt så kommer JSON-gemen att försöka gissa sig fram till en lämplig encoding. Det är inte säkert att denna gissningen blir rätt, dock. Då kommer man få det här felet D:

**Comment by oleander** [comment]
Från och med den [här](https://github.com/oleander/Spotify/commit/c2e306b6de1cd14de05b44a66335475f7b0887e5) commiten så kontrollerar jag så att JSON-datan verkligen är UTF-8.

Problemet kvarstår dock.
